recs:
  gcp:
    project: ${RECS_GCP_PROJECT}
    bucket: ${RECS_GCS_BUCKET}
  rowmodel:
    path: model/row.csv
  colmodel:
    path: model/col.csv
  usermodel:
    path: model/user.csv
  itemmodel:
    path: model/item.csv
  useritem:
    path: data/recommendation_events.csv